---
title: "Presentaciones"
author: "Juvenal Campos"
date: "2/27/2020"
output: html_document
---

<div class="container-fluid main-container">

<div id="sitio-de-almacenamiento-de-paginas-web" class="section level1">
<h1>Sitio de almacenamiento de Paginas Web</h1>
<div id="presentaciones" class="section level3">

## LNPP-Tech

* **Junio 2021** [Introducción y conceptos básicos de visualización de datos](lnpp_tech/presentacion_dataviz.pdf)

* **Julio 2021** [Visualización de datos en R - Parte Prácitca](lnpp_tech/lnpp_tech_viz_2.pdf)

## Clase de Periodismo de Datos 2021 - MPPP

* **Sesión 1. ** [Introducción a RMarkdown](PdD2021/Sesion1/Presentacion-1.html)

* **Sesión 3. ** [Expresiones regulares con `rebus`](PdD2021/Sesion3/Presentacion3.pdf)

* **Sesión 4. ** [Mapas en `ggplot2`](PdD2021/Sesion4/presentacion4.pdf)

* **Sesión 5. ** [Mapas interactivos con leaflet](PdD2021/Sesion5/presentacion5.pdf)

* **Sesión 6. ** [Visualización interactiva en R](PdD2021/Sesion6/presentacion6.pdf)

* **Sesión 7. ** [Datos Abiertos y Descargas Automatizadas](PdD2021/Sesion7/presentacion7.pdf)

* **Sesión 8 y 9. ** [Descarga de datos de APIs](PdD2021/Sesion8_9/Sesion08_09.pdf)

* **Sesión 10. ** [Web Scraping](PdD2021/Sesion10/presentacion10.pdf)

* **Sesión 13. ** [Introducción a Github](PdD2021/Sesion13/presentacion13.pdf)

* **Sesión 15. ** [Periodismo de datos](PdD2021/Sesion15/presentacion15.pdf)

<br><br><br>

<h2>Clase de Metodos Cuantitativos Aplicados. CIDE - CPRRII, 2020.</h2>
<ol style="list-style-type: decimal">
<li><a href="MCA2020/Sesion1/index.html">Presentación de problemas de Probabilidad con R</a>.</li>
<li><a href="MCA2020/Sesion2/index.html">Solución cuestionario de prueba</a>.</li>
<li><a href="MCA2020/ProblemasSelectos/problemasSelectos.pdf">Problemas selectos previos al primer exámen.</a></li>
</ol>
</div>
</div>

</div>
<br>
<br>

## Clase de Visualización y puesta en página digital. Vis-2020

#### Presentaciones: 

* **Sesión 2.** [Elaboración de mapas en {ggplot2}.](vis2020/Sesion2.pdf)

* **Sesión 3.** [Introducción a la visualización interactiva](vis2020/Sesion3.pdf)

* **Sesión 4.** [Mapas interactivos en Leaflet](vis2020/Sesion4.pdf)

* **Sesión 5.** [R Markdown](https://rpubs.com/Juve_Campos/rmarkdown)

* **Sesión 6.** [Datos Abiertos y Descarga Automática de Datos](vis2020/Sesion6.pdf)

* **Sesión 7.** [Descarga de datos a través de APIs](vis2020/Sesion7.pdf)

* **Sesión 8.** [Introducción al Web Scraping en R](vis2020/Sesion8.pdf)

* **Sesión 11.** [Expresiones Regulares con Rebus](vis2020/Sesion11.pdf)


